#title in header
title: "å°å—è’è‡ªç•™åœ°"

#main info
#owner
owner: "Erasernoob"
email: erasernoob@outlook.com
info: "ä¸€ä¸ªåœ°çƒäºº"
#description
desc: "è®°å½•å¥‡å¥‡æ€ªæ€ªçš„æƒ³æ³•ä»¥åŠå­¦ä¹ å’ŒæŠ˜è…¾è®°å½•å¤„"

#menu
menu:
  Works: /Works
  About: ./HTML/FireWorks/index.html

#index/main page max show posts (in number)
max_post: 4

# Colors use hex color without #
# Theme color
tcolor: 0FA0CE

# Define path to user css
#(could be also located outside of theme)
# Relative to source/ directory
usercss: css/user.css

# social profile at the footer/bottom
footer: true
placename: Earth
placelink: https://en.wikipedia.org/wiki/Earth
github: https://github.com/erasernoob
linkedin: https://linkedin.com/in/adisaktijrs
twitter: https://twitter.com
instagram: https://instagram.com

# Misc
nanobar: /js/nanobar.min.js
switch_light: â˜€ï¸
switch_dark: ğŸŒ‘

# favicon
favicon: /images/favicon.png
# thumbnail
thumbnail: /images/thumbnail.jpg

article:
  thumbnail: true

# DISQUS comments (sign up to Disqus to get disqus_shortname)
disqus_enabled: false
disqus_shortname: https-adisaktijrs-github-io
